In [3]:
import pandas as np
import matplotlib.pyplot as plt


In [4]:
df=np.read_csv("RRR.csv")

In [5]:
df

age  status
0    21     0.0
1    33     1.0
2    24     0.0
3    28     1.0
4    17     0.0
5    33     1.0
6    23     0.0
7    30     0.0
8    29     1.0
9    22     0.0
10   26     1.0
11   20     0.0
12   24     NaN
13   34     1.0
14   29     1.0
15   16     0.0
16   18     0.0
17   22     0.0
18   26     1.0
19   25     1.0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   age     20 non-null     int64  
 1   status  19 non-null     float64
dtypes: float64(1), int64(1)
memory usage: 448.0 bytes


In [7]:
df.isnull().sum()

age       0
status    1
dtype: int64

In [8]:
han=df['status'].median()

In [9]:
han  #maximum number 0 so out put zero

0.0

In [10]:
df.status=df.status.fillna(han)

In [11]:
df["status"].value_counts()

0.0    11
1.0     9
Name: status, dtype: int64

In [12]:
df

age  status
0    21     0.0
1    33     1.0
2    24     0.0
3    28     1.0
4    17     0.0
5    33     1.0
6    23     0.0
7    30     0.0
8    29     1.0
9    22     0.0
10   26     1.0
11   20     0.0
12   24     0.0
13   34     1.0
14   29     1.0
15   16     0.0
16   18     0.0
17   22     0.0
18   26     1.0
19   25     1.0

In [13]:
x=df[['age']]

In [14]:
x

age
0    21
1    33
2    24
3    28
4    17
5    33
6    23
7    30
8    29
9    22
10   26
11   20
12   24
13   34
14   29
15   16
16   18
17   22
18   26
19   25

In [15]:
y=df["status"]

In [16]:
y

0     0.0
1     1.0
2     0.0
3     1.0
4     0.0
5     1.0
6     0.0
7     0.0
8     1.0
9     0.0
10    1.0
11    0.0
12    0.0
13    1.0
14    1.0
15    0.0
16    0.0
17    0.0
18    1.0
19    1.0
Name: status, dtype: float64

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=.4,random_state=1)

In [19]:
xtest

age
3    28
16   18
6    23
10   26
2    24
14   29
4    17
17   22

In [20]:
ytest

3     1.0
16    0.0
6     0.0
10    1.0
2     0.0
14    1.0
4     0.0
17    0.0
Name: status, dtype: float64

In [21]:
from sklearn.linear_model import LogisticRegression

In [22]:
model=LogisticRegression()

In [23]:
model.fit(xtrain,ytrain)

LogisticRegression()

# Output for Logistic Regression

In [24]:
model.predict(xtest)

array([1., 0., 0., 0., 0., 1., 0., 0.])

In [25]:
model.score(xtest,ytest)

0.875

# Output for  Sigmoid function

In [26]:
model.predict_proba(xtest)

array([[0.31579902, 0.68420098],
       [0.96251751, 0.03748249],
       [0.77491344, 0.22508656],
       [0.50765417, 0.49234583],
       [0.69728108, 0.30271892],
       [0.23594733, 0.76405267],
       [0.974607  , 0.025393  ],
       [0.83728287, 0.16271713]])

In [43]:
y_predict=model.predict([[26.5]])

In [44]:
y_predict;

In [45]:
if y_predict==0:
    print("UnMarried")
else:
    print('Married')
    

Married


In [35]:
model.predict_proba([[26.1]]) #first part not maried second part maried percentage


array([[0.49760773, 0.50239227]])